name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip openjdk-8-jdk lib32stdc++6 lib32z1
          pip install --upgrade pip
          pip install --upgrade buildozer cython

      - name: Install Android SDK
        run: |
          # Install required tools
          sudo apt-get install -y wget unzip
          
          # Download the latest SDK command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          
          # Unzip SDK command line tools
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          
          # Set environment variables
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
          export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

          # Install necessary SDK components, including build-tools, NDK, and platform tools
          echo "y" | sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.4.7075529" "tools" "cmdline-tools;latest"

          # Ensure sdkmanager is updated (sometimes this resolves missing tools)
          sdkmanager --update

          # Verify the build-tools directory
          echo "Checking build-tools for aidl..."
          find $ANDROID_SDK_ROOT/build-tools -name "aidl" || (echo "Aidl not found in build-tools directory" && exit 1)

      - name: Verify AIDL Availability
        run: |
          # Check if aidl is available in the build-tools directory
          echo "Checking for aidl..."
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
          export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
          
          if ! find $ANDROID_SDK_ROOT/build-tools -name "aidl" &> /dev/null; then
            echo "Aidl not found, please install it."
            exit 1
          else
            echo "Aidl is available."
          fi

      - name: Cache Buildozer Global Directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer Directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
          export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
          buildozer android debug

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: .buildozer/android/platform/build/outputs/apk/debug/*.apk
